Pagination component
spatie/vue-data-component pull request #36
Opened 2018-09-21 14:12 UTC by AdrianMrn

2018-09-21 15:56 UTC, sebastiandedeyne requested changes

2018-09-21 15:56 UTC, sebastiandedeyne commented on docs/pages/ajax-card-layout.vue
> +            pageCountKey="pageCount"
Kebab case :D

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataComponent.js
>          pageCountKey: { default: null },
You can add a `pageCount` default here (and drop the explicitly passed prop from the previous comment)

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +                range.unshift("...");
`...` -> `…`

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +            <ul slot-scope="{ pages }" class="mt-4 flex justify-center">
This `slot-scope` can go

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +                    onClick={() => this.$emit('change-page', (this.page === this.pageCount) ? this.page : this.page + 1)}
Move this to it's own method and use it at line 71 too?

Also, keep even names like html does -> no "spaces", first subject then action. -> `pagechange`

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +                        { page.disabled &&
Maybe use a ternary operator instead?

```js
{page.disabled ? (
    page.number
) : (
    <button></button>
)}
```

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +                <li>
These should get a disabled state and not be a button when we're on the first/last page

2018-09-21 15:56 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +        paginator() {
Since this is just an array of page objects, should we call it `pages` instead?

2018-09-24 08:08 UTC, AdrianMrn commented on src/components/DataPaginator.js
> +        paginator() {
👌

2018-09-24 08:09 UTC, AdrianMrn commented on src/components/DataPaginator.js
> +                        { page.disabled &&
👍

2018-09-24 08:10 UTC, AdrianMrn commented on src/components/DataComponent.js
>          pageCountKey: { default: null },
@sebastiandedeyne https://github.com/spatie/vue-data-component/blob/b0ce1bb23a2e186596f48af54bf3a5f622ef4f9d/src/components/DataComponent.js#L226-L232
Line 231 wouldn't work anymore (for local data sources)

2018-09-24 08:13 UTC, AdrianMrn commented on src/components/DataPaginator.js
> +                <li>
@sebastiandedeyne Like this?
```jsx
<li>
    { this.page === this.pageCount ? '>' : (
        <button
            onClick={() => this.pageChange((this.page === this.pageCount) ? this.page : this.page + 1)}
        >
        &gt;
        </button>
    )}
</li>
```

2018-09-24 08:23 UTC, sebastiandedeyne commented on src/components/DataComponent.js
>          pageCountKey: { default: null },
We can work around this by attempting to retrieve the page count, and fall back on our calculation if nothing was returned.

```js
const pageCount = get(fetchResult, this.pageCountKey);

if (pageCount === undefined) { 
    return pageCount;
}
```

Remember, `0` is a valid page count!

2018-09-24 08:24 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +                <li>
On second though, maybe keep the `button` element here with `disabled` 😅 I think it's more semantic like that

2018-09-24 08:25 UTC, sebastiandedeyne commented
One more general comment: could you look into aria attributes and see if they have anything regarding pagination that we could/should add?

2018-09-24 09:15 UTC, AdrianMrn commented
> One more general comment: could you look into aria attributes and see if they have anything regarding pagination that we could/should add?

Done! Used http://www.a11ymatters.com/pattern/pagination/ and https://www.w3.org/TR/html5/dom.html#do-not-set

2018-09-24 15:08 UTC, sebastiandedeyne requested changes

2018-09-24 15:08 UTC, sebastiandedeyne commented on docs/pages/ajax-card-layout.vue
> +            return axios.get(`${baseUrl}?${queryString}`).then(response => ({
This can stay, we still only care about Rick :)

2018-09-24 15:08 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +                            onClick={ () => this.pageChange((this.page === 1) ? this.page : this.page - 1) }
Can you run `yarn format` before merging? I think prettier should strip the spaces after `{` and before `}`

2018-09-24 15:08 UTC, sebastiandedeyne commented on docs/pages/ajax-card-layout.vue
> +                <data-paginator :page="query.page" :page-count="pageCount" @page-change="query.page = $event"></data-paginator>
`page-change` shouldn't exist, it should be an `input` event so `page` can be bound with `v-model`

2018-09-24 15:08 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +            <nav aria-label="Pagination Navigation">
You're going to need to install the necessary Babel plugins to support JSX (and run `yarn build` before to ensure it all transpiles well)

https://github.com/vuejs/babel-plugin-transform-vue-jsx

2018-09-25 08:27 UTC, AdrianMrn commented on docs/pages/ajax-card-layout.vue
> +                <data-paginator :page="query.page" :page-count="pageCount" @page-change="query.page = $event"></data-paginator>
slim!

2018-09-25 11:30 UTC, AdrianMrn commented on src/components/DataPaginator.js
> +            <nav aria-label="Pagination Navigation">
installed plugins & added them to `.babelrc` but I must've done something wrong, it's not working yet :#

2018-09-25 15:24 UTC, sebastiandedeyne approved these changes

2018-09-25 15:25 UTC, sebastiandedeyne commented on src/components/DataPaginator.js
> +            <nav aria-label="Pagination Navigation">
Apparently the Rollup Babel plugin must come before the Rollup Commonjs plugin

2018-09-25 15:25 UTC, merged